# Extends workspace-wide root .vale.ini
StylesPath = .github/styles
MinAlertLevel = suggestion
IgnoredScopes = code, tt, pre, img, blockquote

[*.md]
BasedOnStyles = Vale, write-good

# write-good rules (selective)
write-good.Ellipses = YES
write-good.Lexisms = YES
write-good.Passive = YES
write-good.ThereIs = YES
write-good.TooWordy = YES
write-good.Weasel = YES
